### ISSUE TITLE
Out dated Version 

### ISSUE THREAD

**Issue by Rex-XII-Music** [betterphp/BloodMoon#139]
I'm a user of this fantastic plugin and had a fun time using it but since Minecraft 1.20 and 20.1 came out this plugin is outdated and no more working with new version!

Kindly update this plugin so new version user could also enjoy it.
Rex-XII

**Comment by Rex-XII-Music** [comment]
@john-f-chamberlain @betterphp

**Comment by Rex-XII-Music** [comment]
Anyone?

**Comment by john-f-chamberlain** [comment]
@Rex-XII-Music I fixed a typo in this plugin in 2012, I never contributed any actual code.
Considering this plugin has not been developed in over 9 years, I'd consider it to be dead.

**Comment by Rex-XII-Music** [comment]
☠️ But please can't you update it?

**Comment by john-f-chamberlain** [comment]
Unfortunately no, I cannot. The developer might be able to, but since like I said it hasn't been touched in 9 years, it's unlikely.

**Comment by Rex-XII-Music** [comment]
So can you contact the Dev for it?

**Comment by betterphp** [comment]
Hey sorry I missed the notification for this.

Unfortunately it'd be way too much work to get this working with the new version.

**Comment by Rex-XII-Music** [comment]
Ohh ok :(

**Comment by betterphp** [comment]
Sorry :(

If someone else wants to do a pull request I'll happily accept it and recommend their fork as the updated version in the readme.
